services:
  postgres:
    image: postgres:16
    container_name: MovieHubApi-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: movieHubDB
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ..
      dockerfile: MovieHub/Dockerfile
    container_name: MovieHubApi-Api
    depends_on:
      postgres:
        condition: service_healthy  # <-- espera o postgres estar PRONTO
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=movieHubDB;Username=postgres;Password=admin

volumes:
  postgres_data: